package com.stackroute.swisit.crawler;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.stackroute.swisit.crawler.domain.CrawlerResult;
import com.stackroute.swisit.crawler.domain.SearcherResult;
import com.stackroute.swisit.crawler.exception.DOMNotCreatedException;
import com.stackroute.swisit.crawler.repository.CrawlerRepository;
import com.stackroute.swisit.crawler.repository.Neo4jRepository;
import com.stackroute.swisit.crawler.service.DOMCreatorService;
import com.stackroute.swisit.crawler.service.MasterScannerService;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.web.WebAppConfiguration;

import java.io.IOException;
import java.text.ParseException;

/**
 * Class to test Service class of DOM creation
 */
@RunWith(SpringJUnit4ClassRunner.class)
@WebAppConfiguration
@ContextConfiguration()
public class DOMCreatorServiceImplTest {
    @MockBean
    private DOMCreatorService domCreatorService;

    @MockBean
    private MasterScannerService masterScannerService;

    @MockBean
    private CrawlerRepository crawlerRepository;

    @MockBean
    private Neo4jRepository neo4jRepository;

    @MockBean
    private SearcherResult searcherResult;

    @MockBean
    private CrawlerResult crawlerResult;

    @Test
    public void constructDOM() throws ParseException, JsonProcessingException, IOException,DOMNotCreatedException {
        Document document = Jsoup.parse("\n" +
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" +
                "<HTML>\n" +
                "<HEAD>\n" +
                "\t<TITLE>Diffusion Limited Aggregation (DLA) java applet</TITLE>\n" +
                "</HEAD>\n" +
                "<BODY BGCOLOR=\"#fdfff4\">\n" +
                "<ADDRESS><B><FONT SIZE=5>Diffusion Limited Aggregation</FONT></B><FONT SIZE=4>\n" +
                "(a fractal growth model)</FONT></ADDRESS>\n" +
                "<HR>\n" +
                "<P ALIGN=CENTER><APPLET CODE=\"dla.class\" ALIGN=BOTTOM WIDTH=600 HEIGHT=420>\n" +
                "\t<PARAM NAME=\"SGI_SRC\" VALUE=\"/usr/people/lam/public_html/dla/dla.class\">\n" +
                "</APPLET></P>\n" +
                "<P><FONT COLOR=\"#008000\">Instruction: </FONT>Clusters of Diffusion\n" +
                "Limited Aggregation (DLA) can be generated by pressing the &quot;Grow&quot;\n" +
                "button. To see more details about the growth process, press the &quot;Grow\n" +
                "slowly&quot; button. Particles added to the aggregate at different\n" +
                "time are shaded using different colors. \n" +
                "</P>\n" +
                "</P>\n" +
                "<P>&quot;<FONT COLOR=\"#008000\">Grow&quot;:</FONT> This button\n" +
                "initiates a much faster simulation. The launching circle is set to be\n" +
                "the smallest circle inscribing the cluster while the killing circle\n" +
                "is 5 times as large to approximate an infinite killing circle.\n" +
                "Dramatic improvement in the efficiency is due to allowing every\n" +
                "walker to jump over the longest possible distance which is still\n" +
                "clear of any part of the cluster. Again, we check the position of\n" +
                "every particle in the cluster to determine how far a walker can jump.\n" +
                "</P>\n" +
                "<TABLE BORDER=0 CELLPADDING=2 CELLSPACING=5>\n" +
                "\t<TR>\n" +
                "\t\t<TD>\n" +
                "\t\t\t<P><FONT COLOR=\"#800000\"><A HREF=\"dla100m.html\"><FONT COLOR=\"#000080\"><IMG SRC=\"dla100ms.gif\" NAME=\"Graphic1\" ALIGN=BOTTOM WIDTH=70 HEIGHT=73 BORDER=1></FONT></A></FONT></P>\n" +
                "\t\t</TD>\n" +
                "\t\t<TD>\n" +
                "\t\t\t<P>Please click to thumbnail to see two large\n" +
                "\t\t\tDLA clusters. More about physicists' views of\n" +
                "\t\t\tDLA can be found in the book &quot;Fractal\n" +
                "\t\t\tGrowth Phenomena&quot; by Vicsek.&nbsp;</P>\n" +
                "\t\t</TD>\n" +
                "\t</TR>\n" +
                "</TABLE>\n" +
                "<P STYLE=\"line-height: 100%\"><FONT SIZE=2><FONT COLOR=\"#00ae00\">Author:\n" +
                "<A HREF=\"http://apricot.ap.polyu.edu.hk/\">Chi-Hang\n" +
                "Lam</A>, Applied Physics, Hong Kong Polytechnic University\n" +
                "(</FONT><A HREF=\"../dla.tgz\">complete\n" +
                "package</A>, <A HREF=\"dla.java\">java\n" +
                "source code</A>)</FONT></P>\n" +
                "</BODY>\n" +
                "</HTML>\n");
        Document doc= domCreatorService.constructDOM("http://apricot.polyu.edu.hk/~lam/dla/dla.html");
        Document document1 = document;
        Assert.assertEquals(document,document1);
    }
}
