spring:
  data:
    neo4j:
      uri: http://172.23.239.174:7474
      username: neo4j
      password: root123
    mongodb:
      authentication-database: admin
      database: swisit
      username: superAdmin
      password: admin123
      port: 27017
  application:
    name: documentparser 
server:
  port: 8070
brokerid: 172.23.239.165:9092
topic-fromconsumer: todocumentparser
topic-toproducer: tointentparser

eureka:
  client:
    service-url:
      defaultZone: http://172.23.239.153:8761/eureka/
  instance:
    prefer-ip-address: true  
      