spring:
  data:
    neo4j:
      uri: http://172.23.239.174:7474
      username: neo4j
      password: root123
  application:
    name: intentparser
brokerid: 172.23.239.165:9092
topic-fromconsumer: tointentparser
eureka:
  client:
    service-url:
      defaultZone: http://172.23.239.153:8761/eureka/
  instance:
    prefer-ip-address: true  

  