#spring:
#  data:
#    mongodb:
#      authentication-database: admin
#      database: swisit
#      username: superAdmin
#      password: admin123
#      port: 27017
brokerid: 172.23.239.165:9092
initialtopic: tosearcher
publishertopic: testcontrol
url: https://www.googleapis.com/customsearch/v1?q=
key: engineid
server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://172.23.239.153:8761/eureka/
  instance:
    prefer-ip-address: true  
 
